spring.application.name=MovieSearchAPI
server.port = 8081
movie.api.url=https://jsonmock.hackerrank.com/api/movies/search/

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=mysecretkeymysecretkeymysecretkey
